<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.80.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\proto\contracts\proto\auth\auth.proto" GrpcServices="Client" ProtoRoot="..\..\proto\contracts\proto\" />
    <Protobuf Include="..\..\proto\contracts\proto\training\training.proto" GrpcServices="Client" ProtoRoot="..\..\proto\contracts\proto\" />
    <Protobuf Include="..\..\proto\contracts\proto\ai\ai.proto" GrpcServices="Client" ProtoRoot="..\..\proto\contracts\proto\" />
  </ItemGroup>
</Project>
